import os

CC = 'clang'

CFLAGS = " ".join([
    '-Weverything',
    '-std=c11'
])

FILES = [
    'main.c',
    'lexer.c'
]

TEST_FILES = FILES[1:]
TEST_FILES.append('tests.c');

ragel = Builder(action = 'ragel -G2 $SOURCE -o $TARGET',
                suffix = '.c',
                src_suffix = '.rl')

env = Environment( CC=CC
                  ,CCFLAGS=CFLAGS
                  ,BUILDERS={'Ragel' : ragel} )

#Enable coloured output from Clang
env['ENV']['TERM'] = os.environ['TERM']

lex = env.Ragel('lexer.rl')
roth = env.Program('roth', FILES)

tests = env.Program('tests', TEST_FILES);
check = env.Command(target = 'check',
                    source = 'tests',
                    action = './' + tests[0].path)
env.Depends(check, tests)
