CC = 'clang'

WARNINGS=" ".join([
    '-Weverything'
])

ragel = Builder(action = 'ragel -G2 $SOURCE -o $TARGET',
                suffix = '.c',
                src_suffix = '.rl')

env = Environment( CC=CC
                  ,CCFLAGS=WARNINGS
                  ,BUILDERS={'Ragel' : ragel} )
